---

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-ast
  - id: check-merge-conflict
  - id: flake8
#  - id: pyflakes
  - id: double-quote-string-fixer
#  - id: requirements-txt-fixer
  - id: end-of-file-fixer
- repo: local
  hooks:
  - id: pytest
    name: pytest tests/
    entry: pytest --color=yes tests/ -ra -q
    files: ^(.*py)$
    language: python
    additional_dependencies: [pytest, mock, jinja2, pyyaml]
    python_version: python3
    pass_filenames: false
  - id: tox
    name: tox
    entry: tox
    files: ^(.*py)$
    language: python
    additional_dependencies: [tox]
    pass_filenames: false
  - id: profiles
    name: profiles
    entry: bash profile_test.sh
    files: ^(.*profiles.*yaml(.jinja2)?)$
    language: system
    pass_filenames: true
