---
name: "Deploy docs"

# Only run this when the master branch changes
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master

# This job installs dependencies, build the docs, and pushes it to `gh-pages`
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # Install dependencies
      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: "Set up Poetry"
        uses: "abatilo/actions-poetry@v2.1.2"

      - name: "Install dependencies"
        run: |
          poetry install

      # Build the docs
      - name: "Build the docs"
        run: |
          poetry jupyter-book build docs

      # Push the docs' HTML to github-pages
      - name: "GitHub Pages action"
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
